[package]
name = "fluxhead"
version = "0.1.0"
edition = "2024"
authors = ["Markus Stoller"]
description = "A library to decode g64 images"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/markusstoller/fluxhead"

[dependencies]
endian_codec="0.x"
cbm-dos="0.1.1"
spdlog-rs="0.4"